language: java
jdk:
  - oraclejdk8
before_script:
  - wget https://dist.ipfs.io/go-ipfs/v0.4.16/go-ipfs_v0.4.16_linux-amd64.tar.gz -O /tmp/go-ipfs_linux-amd64.tar.gz
  - tar -xvf /tmp/go-ipfs_linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/go-ipfs/
  - ipfs init
  - ipfs daemon --enable-pubsub-experiment &
script:
  - mvn clean verify
